# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=500)),
                ('video_image', models.CharField(max_length=1000)),
                ('video_length', models.CharField(max_length=255)),
                ('video_title', models.CharField(max_length=500)),
                ('video_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_day', models.DateField(auto_now_add=True)),
                ('video_keyword', models.CharField(max_length=255)),
                ('video_quality', models.IntegerField(default=0)),
                ('video_url', models.CharField(max_length=1000)),
                ('video_source', models.CharField(max_length=255)),
                ('video_recomend', models.IntegerField(default=0)),
            ],
        ),
    ]
